<!DOCTYPE html>
<html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>FAQ - Pages - PixelAdmin</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
        <link href="<?= base_url() ?>assets/css/lib/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="<?= base_url() ?>assets/css/lib/pixel-admin.min.css" rel="stylesheet" type="text/css">
        <link href="<?= base_url() ?>assets/css/lib/pages.min.css" rel="stylesheet" type="text/css" attr="1111111">
        <link href="<?= base_url() ?>assets/css/lib/themes.min.css" rel="stylesheet" type="text/css">
    </head>
    <body class="theme-default main-menu-animated page-faq">
        <script>var init = [];</script>
        <div id="main-wrapper">
            <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
                <!-- Main menu toggle -->
                <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>		
                <div class="navbar-inner">
                    <!-- Main navbar header -->
                    <div class="navbar-header">
                        <!-- Logo -->
                        <a href="index.html" class="navbar-brand">
                            <div><img alt="Pixel Admin" src="<?php echo base_url(); ?>assets/images/pixel-admin/main-navbar-logo.png"></div>
                            <?php echo PROJECT_NAME; ?>
                        </a>

                        <!-- Main navbar toggle -->
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

                    </div> <!-- / .navbar-header -->

                    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                        <div>
                            <div class="right clearfix">
                                <ul class="nav navbar-nav pull-right right-navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                                            <img src="<?php echo base_url(); ?>assets/demo/avatars/1.jpg" alt="">
                                            <span><?php echo isset($_SESSION['name'])?$_SESSION['name']:""; ?></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#"><span class="label label-warning pull-right">New</span>Profile</a></li>
                                            <li><a href="#"><span class="badge badge-primary pull-right">New</span>Account</a></li>
                                            <li><a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
                                            <li class="divider"></li>
                                            <li><a href="pages-signin.html"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
                                        </ul>
                                    </li>
                                </ul> <!-- / .navbar-nav -->
                            </div> <!-- / .right -->
                        </div>
                    </div> <!-- / #main-navbar-collapse -->
                </div> <!-- / .navbar-inner -->
            </div>
            <div id="main-menu" role="navigation">
                <div id="main-menu-inner">
                    <?php include_once APPPATH . '/includes/login_menu.phtml'; ?>
                    <?php include_once APPPATH . '/includes/nav_menu.phtml'; ?>
                </div> <!-- / #main-menu-inner -->
            </div>
            <div id="main-menu-bg"></div>