<div class="menu-content top" id="menu-content-demo">
    <div>
        <div class="text-bg"><span class="text-slim">Welcome,</span> <span class="text-semibold">John</span></div>
        <img src="<?php echo base_url()?>assets/demo/avatars/1.jpg" alt="" class="">
            <div class="btn-group">
                <a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-envelope"></i></a>
            </div>
            <a href="#" class="close">&times;</a>
    </div>
</div>
