<html>
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Sign In - <?=PROJECT_NAME?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <?php
            load_assets('css',$css_files);
            load_assets('js',$js_files);
        ?>
    </head>
    <body class="theme-default page-signin">
        <div id="page-signin-bg">
            <div class="overlay"></div>
            <img src="<?=base_url()?>assets/demo/signin-bg-1.jpg" alt="">
        </div>
        <div class="signin-container">
            <div class="signin-info">
                <a href="<?=base_url()?>" class="logo"><?=PROJECT_NAME?></a>
                <div class="slogan"><?=PROJECT_SLOGAN?></div> <!-- / .slogan -->
                <ul>
                    <?php foreach($work_details as $value){ ?>
                    <li><i class="fa fa-sitemap signin-icon"></i> <?=$value?></li>
                    <?php } ?>
                </ul>
            </div>
            <div class="signin-form">
                <?php $action=base_url($current_module.''); 
                      $attributes=array('id'=>'signin-form_id','method'=>'post','novalidate'=>'novalidate');
                      echo form_open($action,$attributes); 
                ?>
                    <div class="signin-text">
                        <span>Sign In to your account</span>                                                
                    </div>
                <div><?php if($errorMsg!=""){ echo $errorMsg; }?></div>
                    <div class="form-group w-icon">                        
                        <input type="text" placeholder="Username or email" class="form-control input-lg" id="username_id" name="username" value="<?php echo set_value('username'); ?>">
                        <span class="fa fa-user signin-form-icon"></span>
                        <?php echo form_error('username'); ?>
                    </div>
                    <div class="form-group w-icon">
                        <input type="password" placeholder="Password" class="form-control input-lg" id="password_id" name="password" value="<?php echo set_value('password'); ?>">
                        <span class="fa fa-lock signin-form-icon"></span>
                        <?php echo form_error('password'); ?>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="signin-btn bg-primary" value="SIGN IN">
                        <a id="forgot-password-link" class="forgot-password" href="javascript::void(0)">Forgot your password?</a>
                    </div>
                </form>
                <div id="password-reset-form" class="password-reset-form">
                    <div class="header">
                        <div class="signin-text">
                            <span>Password reset</span>
                            <div class="close">×</div>
                        </div>
                    </div>
                    <?php   
                        $action=base_url($current_module.'/change_password'); 
                        $attributes=array('id'=>'password-reset-form_id','method'=>'post','novalidate'=>'novalidate');
                        echo form_open($action,$attributes); 
                    ?>                    
                        <div class="form-group w-icon">
                                <input type="text" placeholder="Enter your email" class="form-control input-lg" id="p_email_id" name="email">
                                <span class="fa fa-envelope signin-form-icon"></span>
                                <?php echo form_error('email'); ?>
                        </div>
                        <div class="form-actions">
                            <input type="submit" class="signin-btn bg-primary" value="SEND PASSWORD RESET LINK">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

