<?php
    $id="";
    $client_id="";
    $product_id="";
    $price="";
    $unit_id="";
    $disable="";
    if( $mode=="Edit" && count($price_details)>0){
    $id=  isset($price_details->id)?$price_details->id:"";
    $client_id=  isset($price_details->client_id)?$price_details->client_id:"";
    $product_id=  isset($price_details->product_id)?$price_details->product_id:"";
    $unit_id=  isset($price_details->unit_id)?$price_details->unit_id:"";
    $price=isset($price_details->price)?$price_details->price:"";
    $year=isset($price_details->year)?$price_details->year:"";
    $disable="disabled='true'";
    }
?>
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/lib/select2.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/lib/bootstrapValidator.css'); ?>" />
    <div id="content-wrapper">
        <div class="alert alert-danger alert-dark" id="error_msg_container">
            <button data-dismiss="alert" class="close" type="button">×</button>
            <i class="fa fa-bell"></i> <span id="error_msg">Change a few things up and try submitting again.</span>
        </div>
        <div class="page-header">
            <h1 class="col-sm-12"><?="$mode Price"?></h1>
        </div>
        <div class="row">
            <hr class="visible-xs no-grid-gutter-h">
        </div>
        <div class="panel colourable">
            <div class="panel-heading">
                <span class="panel-title"><?=$mode." Price from here"?></span>
            </div>
            <div class="panel-body">                        
                    <?php   
                        $action_url = site_url($currentModule.'/submit');
                        $attributes=array('id'=>'defaultForm','method'=>'post');
                        echo form_open($action_url,$attributes);
                    ?>
                    <input type="hidden" name="id" id="id" value="<?=isset($id)?$id:""?>">
                    <input type="hidden" name="mode" id="mode" value="<?=isset($mode)?$mode:""?>">
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="client_id">Client Name</label>
                        <div class="col-sm-9">
                            <select id="client_id" name="client_id" <?=$disable?>>
                                <option value="">Select Client Name</option>
                                <?php for($i=0;$i<count($client_details);$i++){
                                    $selected=$client_details[$i]->id==$client_id?"selected='selected'":"";
                                ?>
                                <option <?=$selected?> value="<?=$client_details[$i]->id?>"><?=$client_details[$i]->name?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="product_id">Product Name</label>
                        <div class="col-sm-9">
                            <select id="product_id" name="product_id" <?=$disable?>>
                                <option value="">Select Product Name</option>
                                <?php for($i=0;$i<count($product_details);$i++){
                                    $selected=$product_details[$i]->id==$product_id?"selected='selected'":"";
                                ?>
                                <option <?=$selected?> value="<?=$product_details[$i]->id?>"><?=$product_details[$i]->name?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="price">Price</label>
                        <div class="col-sm-9">
                            <input type="text" placeholder="Price" class="form-control" id="price" name="price" value="<?=$price?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="year">For Year</label>
                        <div class="col-sm-9">
                            <select id="year" name="year" <?=$disable?>>
                                <option value="">Select Year Name</option>
                                <?php for($i=2016;$i<=2050;$i++){
                                    $selected=$i==$year?"selected='selected'":"";
                                ?>    
                                <option <?=$selected?> value="<?=$i?>"><?=$i?></option>
                                <?php }?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button id="btn-msr-sheet" type="submit" class="btn btn-primary">Submit</button>
                            <button class="btn btn-cancel" type="button" onclick="javascript:window.location.href=<?php echo "'".site_url($currentModule)."/index"."'"; ?>">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
         </div>
        </div> 
        <script>var ROOT_URL= "<?=base_url()?>";</script>
<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>-->
        <script src="<?=base_url()?>assets/js/lib/jquery.min.js"></script>
        <script src="<?=base_url()?>assets/js/lib/bootstrap.min.js"></script>
        <script src="<?=base_url()?>assets/js/lib/bootstrapValidator.js"></script>
        <script src="<?=base_url()?>assets/js/lib/pixel-admin.min.js"></script>
        <script src="<?=base_url()?>assets/js/custom/common.js"></script>
        <script src="<?=base_url('assets/js/custom/'.$currentModule.'.js')?>"></script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
    </body>
</html>
