<?php
    $id=$product_details->id;
    $name=  isset($product_details->name)?$product_details->name:"";
    $seller_id=  isset($product_details->seller_id)?$product_details->seller_id:'';
    $seller_name=  isset($product_details->seller_name)?$product_details->seller_name:'';
    $unit_id=  isset($product_details->unit_id)?$product_details->unit_id:'';
    $unit_name=  isset($product_details->unit_name)?$product_details->unit_name:'';
?>
            <div id="content-wrapper">
                <div class="page-header">
                    <form method="POST"  id="frmListView" name="frmListView">
                        <h1 class="col-sm-12"><?=" Add ".$currentModule?></h1>
                    </form>
                </div>
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                </div>

                <div class="row">
                    <?php   
                        $action_url = site_url($currentModule.'/submit');
                        $attributes=array('id'=>'defaultForm','method'=>'post');
                        echo form_open($action_url,$attributes);
                    ?>
                        <input type="hidden" name="id" id="id" value="<?=isset($id)?$id:""?>">
                        <input type="hidden" name="mode" id="mode" value="<?=isset($mode)?$mode:""?>">
                        <div class="panel-heading"> <span class="panel-title">Add Product Details Here</span> </div>
                        <div class="panel-body">
                            <label class="col-sm-2">Name of Product:</label>
                            <div class="col-sm-2"><?=$name?></div>

                            <label class="col-sm-2">Seller Name:</label>
                            <div class="col-sm-2"><?=$seller_name?></div>
                            
                            <label class="col-sm-2">Unit:</label>
                            <div class="col-sm-2"><?=$unit_name?></div>
                            <div class="col-sm-12">&nbsp;</div>
                            <div class="col-sm-12">
                                <button class="btn btn-cancel" type="button" onclick="javascript:window.location.href=<?php echo "'".site_url($currentModule)."/index"."'"; ?>">Show List</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
         </div>
        </div>
<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>-->
        <script src="<?=base_url()?>assets/js/lib/jquery.min.js"></script>
        <script src="<?=base_url()?>assets/js/lib/bootstrap.min.js"></script>
        <script src="<?=base_url()?>assets/js/lib/bootstrapValidator.js"></script>
        <script src="<?=base_url()?>assets/js/lib/pixel-admin.min.js"></script>
        <script src="<?=base_url()?>assets/js/custom/common.js"></script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
    </body>
</html>

